# Generated by Django 3.2 on 2021-08-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='管理员id')),
                ('username', models.CharField(default=None, max_length=100, verbose_name='用户名')),
                ('password', models.CharField(default=None, max_length=32, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '管理员',
                'db_table': 'admin',
            },
        ),
    ]
