# Generated by Django 3.2 on 2021-08-02 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128, verbose_name='文件名')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('url', models.CharField(max_length=128, verbose_name='路径')),
                ('md5_name', models.CharField(max_length=64, verbose_name='加密名称')),
                ('removed', models.IntegerField(default=0, verbose_name='已删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name_plural': '文件',
                'db_table': 'user_file',
            },
        ),
    ]
