# Generated by Django 3.1.2 on 2021-06-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(default=None, max_length=100, verbose_name='用户名')),
                ('password', models.CharField(default=None, max_length=32, verbose_name='密码')),
                ('name', models.CharField(default=None, max_length=100, null=True, verbose_name='真实姓名')),
                ('birthday', models.DateTimeField(default=None, max_length=200, null=True, verbose_name='出生日期')),
                ('sex', models.CharField(default=None, max_length=1, null=True, verbose_name='性别')),
                ('telephone', models.CharField(default=None, max_length=11, null=True, verbose_name='电话')),
                ('email', models.EmailField(default=None, max_length=100, verbose_name='邮件地址')),
                ('code', models.CharField(default=None, max_length=50, null=True, verbose_name='激活码（要求唯一）')),
                ('status', models.CharField(default=None, max_length=1, null=True, verbose_name='激活状态')),
                ('avatar', models.ImageField(default=None, max_length=200, null=True, upload_to='media/user/avatar', verbose_name='头像路径')),
                ('date_joined', models.DateTimeField(default=None, null=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name_plural': '用户登录',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.CharField(max_length=100, verbose_name='图片的相对路径')),
                ('uploadTime', models.DateTimeField(default=None, null=True, verbose_name='上传时间')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo.user', verbose_name='用户绑定')),
            ],
            options={
                'verbose_name_plural': '图片表',
                'db_table': 'image',
            },
        ),
    ]
