# Generated by Django 3.2 on 2021-08-04 20:11

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(default=None, max_length=100, verbose_name='用户名')),
                ('password', models.CharField(default=None, max_length=32, verbose_name='密码')),
                ('name', models.CharField(default=None, max_length=100, null=True, verbose_name='真实姓名')),
                ('birthday', models.DateTimeField(default=None, max_length=200, null=True, verbose_name='出生日期')),
                ('sex', models.CharField(default=None, max_length=1, null=True, verbose_name='性别')),
                ('telephone', models.CharField(default=None, max_length=11, null=True, verbose_name='电话')),
                ('email', models.EmailField(default=None, max_length=100, unique=True, verbose_name='邮件地址')),
                ('status', models.CharField(default=None, max_length=1, null=True, verbose_name='激活状态')),
                ('date_joined', models.DateTimeField(default=None, null=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name_plural': '用户登录',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='激活码（要求唯一）')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=builtins.callable, to='user.user', verbose_name='关联的用户')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-c_time'],
            },
        ),
    ]
